# The URL the site will be built for
theme = "cereal"
author = "antipeth"
base_url = "https://blog.0pt.icu"
title = "世纪大道"
description = "你在世纪大道东门"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
minify_html = true

build_search_index = false
generate_feeds = true

[markdown]
render_emoji = true

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
# Put all your custom variables here
menu = [
    { name = "/home", url = "/", weight = 1 },
    { name = "/posts", url = "/posts", weight = 2 },
    { name = "/links", url = "/links", weight = 3 },
    { name = "/about", url = "/about", weight = 4 },
]
social = [{ name = "github", url = "https://github.com/antipeth", weight = 1 }]
toc = true
tracking_scripts = [
'<script defer src="https://umami.0pt.dpdns.org/script.js" data-website-id="db91a9df-01cd-4d4c-9a58-46f63001928d"></script>',
'<script data-goatcounter="https://goatcounter.0pt.dpdns.org/count" async src="//goatcounter.0pt.dpdns.org/count.js"></script>',
]
